#pragma config(Sensor, port6,  b1,             sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          m1,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          m2,            tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		setMotorSpeed(m1, 50);
		setMotorSpeed(m2, 0);

		waitUntil(getBumperValue(b1) == 1);
		{
//			flip = -1 * flip;
		repeatUntil(getBumperValue(b1) == 1)
    {
      	setMotorSpeed(m2, 50);
		setMotorSpeed(m1, 0);
			sleep(500);
    }
		}

	}
}
