#pragma config(Sensor, port6,  b1,             sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          m1,            tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
			int flip = -1;
			int preVal = 0;

	repeat(forever)
	{
		int valBumper = getBumperValue(b1);

		if (valBumper == preVal)
    {
      //values don't change
    }
    else
    {
      flip = -1* flip;
    }
    setMotorSpeed(m1, 50*flip);

    preVal = valBumper;

    sleep(50);

	}
}
