#pragma config(Sensor, port6,  Bumper,         sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          m1,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          m2,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          m3,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          m4,            tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int valBumper = 0;

	valBumper = getBumperValue(Bumper);
	displayTextLine(1, "%d", valBumper);
	//sleep(1000);

		while( getBumperValue(Bumper) == 0)	// Loop while robot's bumper sensor isn't pressed in.
		{
		}

		valBumper = getBumperValue(Bumper);
	displayTextLine(2, "%d", valBumper);
		sleep(1000);


		setMotorSpeed(m1, 50);		//Set the leftMotor (motor1) to half power (50)
		//setMotorSpeed(m2, 50);  //Set the rightMotor (motor6) to half power (50)
		sleep(1000);//Wait for 2 seconds before continuing on in the program.

			valBumper = getBumperValue(Bumper);
	displayTextLine(3, "%d", valBumper);
			sleep(1000);

}
