#pragma config(Sensor, port3,  TouchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port6,  Bumper,         sensorVexIQ_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
	if (getBumperValue(Bumper) == 0)
 {
   setTouchLEDColor(TouchLED, 0);
 }
 else
 {
   setTouchLEDColor(TouchLED, colorBlue);
   setTouchLEDBrightness(TouchLED, 100);
  }
 }
}
